BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-myphone-security"
BBFILE_PATTERN_meta-myphone-security = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-myphone-security = "9"

LAYERDEPENDS_meta-myphone-security = "core"
LAYERSERIES_COMPAT_meta-myphone-security = "scarthgap"
