BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-myphone-update"
BBFILE_PATTERN_meta-myphone-update = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-myphone-update = "10"

LAYERDEPENDS_meta-myphone-update = "core"
LAYERSERIES_COMPAT_meta-myphone-update = "scarthgap"
