name: Yocto CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: crops/poky:scarthgap
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git safe directory
        run: |
          git config --global --add safe.directory /__w/my-rpi4-yocto-os/my-rpi4-yocto-os

      - name: Validate Kas configuration and show recipes
        run: |
          kas shell kas.yml -c "bitbake-layers show-recipes"

      - name: Build MyPhone Image
        run: |
          kas build kas.yml

      - name: Build SDK
        run: |
          kas shell kas.yml -c "bitbake myphone-image -c populate_sdk"

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myphone-image-artifacts
          path: |
            build/tmp/deploy/images/raspberrypi4/myphone-image-raspberrypi4.wic.bz2
            build/tmp/deploy/sdk/*.sh
